### ISSUE TITLE
Crashes on Android 10 (RN / Expo)

### ISSUE THREAD

**Issue by enguerranws** [danilowoz/react-content-loader#174]
## What did you do? 

I followed the provided examples

`import ContentLoader, { Facebook } from 'react-content-loader/native'
function HomeScreen() {
  return <ContentLoader />;
}
`

## What did you expect to happen?
On iOs, everything is working fine. I expected the same on Android.

## What happened actually?
On Android, the app simply crashes when it renders one of the `react-content-loader` component.

**Comment by enguerranws** [comment]
I'll try to run with `adb logcat` to see what's happening on the device and provide more information.

**Comment by enguerranws** [comment]
Here it is:

```
01-15 08:28:56.755  4296  4296 I ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view abi35_0_0.host.exp.exponent.ReactUnthemedRootView{bc4dee9 V.E...... ......ID 0,0-1080,2210 #1}
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: NullPointerException when executing ViewGroup.dispatchDraw method
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: java.lang.NullPointerException: Attempt to read from field 'abi35_0_0.host.exp.exponent.modules.api.components.svg.SVGLength$UnitType abi35_0_0.host.exp.exponent.modules.api.components.svg.SVGLength.unit' on a null object reference
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.VirtualView.relativeOnWidth(VirtualView.java:1)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RectView.getPath(RectView.java:6)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.draw(RenderableView.java:3)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:31)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.GroupView.drawGroup(GroupView.java:12)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.GroupView.draw(GroupView.java:3)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:31)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawChildren(SvgView.java:28)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawOutput(SvgView.java:6)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.onDraw(SvgView.java:4)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:20234)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19109)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:2)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:20237)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19109)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:2)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19100)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:2)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:20237)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19109)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:2)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19100)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:2)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19100)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:2)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19100)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:2)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:20237)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.updateDisplayListIfDirty(View.java:19109)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw(View.java:19962)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at abi35_0_0.com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:1)
01-15 08:28:56.794  4296  4296 E unknown:ReactNative: 	at android.view.View.draw
01-15 08:28:56.892  4296  4296 I Toast   : Show toast from OpPackageName:host.exp.exponent, PackageName:host.exp.exponent
01-15 08:28:56.986  4296  4296 D Event   : No subscribers registered for event class host.exp.exponent.experience.g$d
01-15 08:28:56.986  4296  4296 D Event   : No subscribers registered for event class e.a.a.g
01-15 08:28:57.850  4296  4296 D AndroidRuntime: Shutting down VM
01-15 08:28:57.854  4296  4296 E AndroidRuntime: FATAL EXCEPTION: main
01-15 08:28:57.854  4296  4296 E AndroidRuntime: Process: host.exp.exponent, PID: 4296
01-15 08:28:57.854  4296  4296 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'abi35_0_0.host.exp.exponent.modules.api.components.svg.SVGLength$UnitType abi35_0_0.host.exp.exponent.modules.api.components.svg.SVGLength.unit' on a null object reference
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.VirtualView.relativeOnWidth(VirtualView.java:1)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RectView.getPath(RectView.java:6)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.draw(RenderableView.java:3)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:31)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.GroupView.drawGroup(GroupView.java:12)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.GroupView.draw(GroupView.java:3)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:31)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawChildren(SvgView.java:28)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawOutput(SvgView.java:6)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.onDraw(SvgView.java:4)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.draw(View.java:20234)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19109)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.854  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19069)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3416)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3193)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2562)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1532)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7419)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:819)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:201)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6810)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
01-15 08:28:57.855  4296  4296 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by enguerranws** [comment]
Got it, was an issue with `react-native-svg`. I had to stick to version `9.9.2` as recommanded by the Expo team, as per https://github.com/expo/expo/issues/5888#issuecomment-539021450

**Comment by danilowoz** [comment]
Thanks for letting me know the solution
